backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "audiobooks"
    label: "Audiobooks"
    folder: "content/audiobooks"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Audio File URL", name: "audio", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
